// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArvPpOo0_LgJ2o7TUQDnNNHQYsqNxmEOk',
    appId: '1:703448248677:web:b3398eb01f107f6d8c318c',
    messagingSenderId: '703448248677',
    projectId: 'example1-63ad7',
    authDomain: 'example1-63ad7.firebaseapp.com',
    storageBucket: 'example1-63ad7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxI-v22KcEoQbE-BbPsyzEK-uHK_-vTGw',
    appId: '1:703448248677:android:93234a574dcbd8988c318c',
    messagingSenderId: '703448248677',
    projectId: 'example1-63ad7',
    storageBucket: 'example1-63ad7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrZiHJVqajPnxdS9AslVFqI_75ukhA4bo',
    appId: '1:703448248677:ios:4d6da489cc28a3338c318c',
    messagingSenderId: '703448248677',
    projectId: 'example1-63ad7',
    storageBucket: 'example1-63ad7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrZiHJVqajPnxdS9AslVFqI_75ukhA4bo',
    appId: '1:703448248677:ios:4d6da489cc28a3338c318c',
    messagingSenderId: '703448248677',
    projectId: 'example1-63ad7',
    storageBucket: 'example1-63ad7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArvPpOo0_LgJ2o7TUQDnNNHQYsqNxmEOk',
    appId: '1:703448248677:web:b6a1eb467cf688cf8c318c',
    messagingSenderId: '703448248677',
    projectId: 'example1-63ad7',
    authDomain: 'example1-63ad7.firebaseapp.com',
    storageBucket: 'example1-63ad7.firebasestorage.app',
  );

}